name: Docker Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Image tag
        required: true
      target:
        description: Dockerfile image target to build
        type: choice
        options:
          - scanservjs-epsonscan2
          - scanservjs-brscan4
          - scanservjs-hplip
          - scanservjs-core
          - scanservjs-user2001
          - scanservjs-core

env:
  DOCKER_CLI_EXPERIMENTAL: "enabled"
  IMAGE_TAG_PACKAGE_NAME: "scanservjs"

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    # - name: Set up QEMU
    #   uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set GitHub user
      run: |
        echo "GH_USER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
    - name: Set image tag
      run:
        echo "IMAGE_TAG=ghcr.io/${{ env.GH_USER }}/${{ env.IMAGE_TAG_PACKAGE_NAME }}:${{ github.event.inputs.tag }}" >> $GITHUB_ENV

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./docker/
        platforms: linux/amd64
        push: true
        tags: ${{ env.IMAGE_TAG }}
        target: ${{ github.event.inputs.target }}
